### ISSUE TITLE
Can't start interpreter due to invalid imports

### ISSUE THREAD

**Issue by nikasakandelidze** [dudupopkhadze/typescript-lox-interpreter#2]
As you can see on the image it's not possible to start program due to invalid import.
I guess it is some kind of problem if case sensitivity/insensitivity on machines/OS-es?

Tried to fix all of these kinds of imports to:
import { Lox } from "./lox";
and everything works like charm.

![image](https://user-images.githubusercontent.com/60848556/188606584-371c56fe-940d-4ee7-a134-837fd3c545cb.png)

**Comment by nikasakandelidze** [comment]
Please see [Pull Request](https://github.com/dudupopkhadze/typescript-lox-interpreter/pull/3) for solving this issue.

**Comment by nikasakandelidze** [comment]
@dudupopkhadze

**Comment by dudupopkhadze** [comment]
Fixed with #4
